postgresql:
  install: false
certmanager-issuer:
  install: false
  email: false
nginx-ingress:
  enabled: false

global:
  hosts:
    domain: exercise.com
    externalIP:
    https: true
  edition: ee
  ingress:
    class: azure/application-gateway
    configureCertManager: false
    tls:
      secretName: tls-secret
  certificates:
    customCAs:
    - secret: tls-secret
  psql:
    host:
    username: psqladmin
    password:
      useSecret: true
      secret: psql-pword
      key: password
  kas:
    enabled: false

gitlab:
  migrations:
    initialRootPassword:
      secret: gitlab-pword
      key: password
  webservice:
    enabled: true
    # ingress:
#   tls:
#     secretName: tls-secret
#     smartcardSecretName: tls-secret

gitlab-pages:
  hpa:
    minReplicas: 1
    maxRelicas: 1

sidekiq:
  minReplicas: 1
  maxRelicas: 1

gitaly:
  persistence:
    size: 4Gi

minio:
  replicas: 1
  # ingress:
#   tls:
#     secretName: tls-secret

registry:
  hpa:
    minReplicas: 1
    maxRelicas: 1
  # ingress:
#   tls:
#     secretName: tls-secret

# Bonus integration
# omniauth:
#   enabled: true
#   autoSignInWithProvider: azure_activedirectory_v2
#   syncProfileFromProvider: ['azure_activedirectory_v2']
#   syncProfileAttributes: ['email']
#   blockAutoCreatedUsers: true
#   autoLinkLdapUser: false
#   autoLinkUser: ['saml']
#   externalProviders: []
#   allowBypassTwoFactor: true
#   allowSingleSignOn: [ 'saml']
#   autoLinkSamlUser: true
#   providers: 
#     - secret: azure_ad
# # https://docs.gitlab.com/charts/charts/globals.html#pod:~:text=Once%20created%2C%20the%20providers%20are%20enabled%20by%20providing%20the%20maps%20in%20configuration%2C%20as%20shown%20below%3A
